adjective1 = input("Enter an adjective: ")
adjective2 = input("Enter an adjective: ")
typeOfBird = input("Enter a type of bird: ")
roomInHouse = input("Enter a room in the house: ")
verbPastTense = input("Enter a past tense verb: ")
verb = input("Enter a verb: ")
relativesName = input("Enter the name of a relative: ")
noun = input("Enter a noun: ")
liquid = input("Enter a liquid: ")
verbEndingInIng = input("Enter a verb ending in ing: ")
partOfBodyPlural = input("Enter a part of the body (plural): ")
pluralNoun = input("Enter a noun (plural): ")
verbEndingInIng2 = input("Enter a verb ending in ing: ")
noun2 = input("Enter a noun: ")


print("It was a " + adjective1 + ", cold November day.")
print("I woke up to the " + adjective2 + " smell of " + typeOfBird + " roasting in the " + roomInHouse + " downstairs.")
print("I " + verbPastTense + " down the stairs to see if I could help " + verb + " the dinner.") 
print("My mom said, See if " + relativesName + " needs a fresh " + noun + ".")
print("So I carried a tray of glasses full of " + liquid + " into the " + verbEndingInIng + " room.")
print("When I got there, I couldn't believe my " + partOfBodyPlural + "!")
print("There were " + pluralNoun + " " + verbEndingInIng2 + " on the " + noun2 + "!")


